const esc = (value) => String(value ?? '').replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)').replace(/[\r\n]+/g, ' ');
const money = (n) => Number(n || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const createPdf = (ops) => {
  const objects = [];
  const add = (body) => { objects.push(body); return objects.length; };
  const font = add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
  const bold = add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');
  const content = ops.join('\n');
  const contentObj = add(`<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`);
  const page = add(`<< /Type /Page /Parent 5 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font} 0 R /F2 ${bold} 0 R >> >> /Contents ${contentObj} 0 R >>`);
  const pages = add(`<< /Type /Pages /Kids [${page} 0 R] /Count 1 >>`);
  const catalog = add(`<< /Type /Catalog /Pages ${pages} 0 R >>`);
  const chunks = ['%PDF-1.4\n'];
  const offsets = [0];
  objects.forEach((body, i) => { offsets.push(Buffer.byteLength(chunks.join(''))); chunks.push(`${i + 1} 0 obj\n${body}\nendobj\n`); });
  const xref = Buffer.byteLength(chunks.join(''));
  chunks.push(`xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`);
  offsets.slice(1).forEach((off) => chunks.push(String(off).padStart(10, '0') + ' 00000 n \n'));
  chunks.push(`trailer\n<< /Size ${objects.length + 1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`);
  return Buffer.from(chunks.join(''));
};

const generateNotePdfBuffer = (grn) => {
  const ops = [];
  const text = (x, y, value, size = 9, isBold = false) => ops.push(`BT /${isBold ? 'F2' : 'F1'} ${size} Tf ${x} ${y} Td (${esc(value)}) Tj ET`);
  const line = (x1, y1, x2, y2) => ops.push(`${x1} ${y1} m ${x2} ${y2} l S`);
  const rect = (x, y, w, h) => ops.push(`${x} ${y} ${w} ${h} re S`);
  const isDebit = grn.noteType === 'Debit Note';
  rect(40, 64, 515, 718);
  text(58, 748, 'JPK METALLICS PVT. LTD.', 15, true);
  text(58, 730, 'Amraberia, Mahishrekha, Uluberia, Howrah - 711303, West Bengal', 9);
  text(370, 748, isDebit ? 'DEBIT NOTE' : 'CREDIT NOTE', 17, true);
  text(370, 726, `Note No: ${grn.noteNo || '-'}`, 9, true);
  text(370, 710, `Date: ${new Date().toLocaleDateString('en-GB')}`, 9);
  line(40, 695, 555, 695);
  text(58, 672, 'Vendor', 9, true); text(180, 672, grn.vendorName || '-', 9);
  text(58, 654, 'PO No / Sub PO', 9, true); text(180, 654, `${grn.poNo || '-'} / ${grn.subPoNo || '-'}`, 9);
  text(58, 636, 'Invoice / Challan', 9, true); text(180, 636, `${grn.invoiceNo || '-'} / ${grn.challanNo || '-'}`, 9);
  text(58, 618, 'Invoice Date', 9, true); text(180, 618, grn.invoiceDate ? new Date(grn.invoiceDate).toLocaleDateString('en-GB') : '-', 9);
  line(40, 592, 555, 592);
  text(58, 570, 'Item Description', 9, true); text(200, 570, grn.itemDescription || '-', 9);
  text(58, 552, 'SKU Code', 9, true); text(200, 552, grn.skuCode || '-', 9);
  text(58, 534, 'Department', 9, true); text(200, 534, `${grn.foundry || ''} / ${grn.department || ''}`, 9);
  line(58, 500, 537, 500); line(58, 470, 537, 470); line(58, 440, 537, 440); line(58, 410, 537, 410);
  [58, 200, 320, 430, 537].forEach((x) => line(x, 500, x, 410));
  text(70, 480, 'Particular', 9, true); text(215, 480, 'Qty', 9, true); text(335, 480, 'Rate', 9, true); text(448, 480, 'Amount', 9, true);
  text(70, 450, isDebit ? 'Short received against bill' : 'Excess received against bill', 9);
  text(215, 450, `${Math.abs(Number(grn.shortExcessQty || 0))} ${grn.uom || ''}`, 9);
  text(335, 450, money(grn.rate || 0), 9);
  text(448, 450, money(grn.noteValue || 0), 9, true);
  text(58, 382, `Invoice / Bill Qty: ${grn.invoiceBillQty || 0} ${grn.uom || ''}`, 9);
  text(58, 364, `Physical Received Qty: ${grn.physicalReceivedQty || grn.receivedQty || 0} ${grn.uom || ''}`, 9);
  text(58, 330, isDebit ? 'Reason: Vendor billed more quantity than physically received.' : 'Reason: Physically received quantity is more than bill quantity.', 9);
  text(58, 300, `Net ${isDebit ? 'Debit' : 'Credit'} Amount: INR ${money(grn.noteValue || 0)}`, 12, true);
  text(58, 150, 'Prepared By', 9, true); text(430, 150, 'Authorized By', 9, true);
  line(58, 170, 170, 170); line(430, 170, 537, 170);
  text(58, 98, 'This is a system generated note from JPK Store & Purchase IMS.', 8);
  return createPdf(ops);
};
module.exports = { generateNotePdfBuffer };
